export const LATEST_PRODUCTS_REQUEST = "LATEST_PRODUCTS_REQUEST"
export const LATEST_PRODUCTS_SUCCESS = "LATEST_PRODUCTS_SUCCESS"
export const LATEST_PRODUCTS_FAIL = "LATEST_PRODUCTS_FAIL"

export const MOST_VIEWED_PRODUCTS_REQUEST = "MOST_VIEWED_PRODUCTS_REQUEST"
export const MOST_VIEWED_PRODUCTS_SUCCESS = "MOST_VIEWED_PRODUCTS_SUCCESS"
export const MOST_VIEWED_PRODUCTS_FAIL = "MOST_VIEWED_PRODUCTS_FAIL"

export const SHOP_PRODUCTS_REQUEST = "SHOP_PRODUCTS_REQUEST"
export const SHOP_PRODUCTS_SUCCESS = "SHOP_PRODUCTS_SUCCESS"
export const SHOP_PRODUCTS_FAIL = "SHOP_PRODUCTS_FAIL"
export const SHOP_PRODUCTS_RESET = "SHOP_PRODUCTS_RESET"

export const SINGLE_PRODUCT_REQUEST = "SINGLE_PRODUCT_REQUEST"
export const SINGLE_PRODUCT_SUCCESS = "SINGLE_PRODUCT_SUCCESS"
export const SINGLE_PRODUCT_FAIL = "SINGLE_PRODUCT_FAIL"
export const SINGLE_PRODUCT_RESET = "SINGLE_PRODUCT_RESET"
