export const LATEST_PRODUCTS_REQUEST = "LATEST_PRODUCTS_REQUEST"
export const LATEST_PRODUCTS_SUCCESS = "LATEST_PRODUCTS_SUCCESS"
export const LATEST_PRODUCTS_FAIL = "LATEST_PRODUCTS_FAIL"

export const POPULAR_PRODUCTS_REQUEST = "POPULAR_PRODUCTS_REQUEST"
export const POPULAR_PRODUCTS_SUCCESS = "POPULAR_PRODUCTS_SUCCESS"
export const POPULAR_PRODUCTS_FAIL = "POPULAR_PRODUCTS_FAIL"

export const ORDER_BY_PRODUCTS_REQUEST = "ORDER_BY_PRODUCTS_REQUEST"
export const ORDER_BY_PRODUCTS_SUCCESS = "ORDER_BY_PRODUCTS_SUCCESS"
export const ORDER_BY_PRODUCTS_FAIL = "ORDER_BY_PRODUCTS_FAIL"
export const ORDER_BY_PRODUCTS_RESET = "ORDER_BY_PRODUCTS_RESET"
