export const SHOWCASE_PRODUCTS_REQUEST = "SHOWCASE_PRODUCTS_REQUEST"
export const SHOWCASE_PRODUCTS_SUCCESS = "SHOWCASE_PRODUCTS_SUCCESS"
export const SHOWCASE_PRODUCTS_FAIL = "SHOWCASE_PRODUCTS_FAIL"
