export const SUBSCRIPTION_CREATE_REQUEST = "SUBSCRIPTION_CREATE_REQUEST"
export const SUBSCRIPTION_CREATE_SUCCESS = "SUBSCRIPTION_CREATE_SUCCESS"
export const SUBSCRIPTION_CREATE_FAIL = "SUBSCRIPTION_CREATE_FAIL"
